name: search_widget
description: A Flutter package which provides a Search Widget for selecting an option from a data list.
version: 1.0.3
author: Ayush P Gupta <ayushpguptaapg@gmail.com>
homepage: https://github.com/apgapg/search_widget

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_keyboard_visibility: ^4.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:



