name: search_widget
description: A Flutter package which provides a Search Widget for selecting an option from a data list.
version: 1.1.2
author: Ayush P Gupta <ayushpguptaapg@gmail.com>
homepage: https://github.com/apgapg/search_widget

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_keyboard_visibility: 5.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:



